AWSTemplateFormatVersion: "2010-09-09"
Description: Criando um EC2 com Apache simples

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP
      VpcId: !Ref "AWS::NoValue"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316 
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>Servidor Apache instalado!</h1>" > /var/www/html/index.html

Outputs:
  EC2PublicIP:
    Description: IP público da EC2
    Value: !GetAtt EC2Instance.PublicIp
