AWSTemplateFormatVersion: "2010-09-09"
Description: Criando EC2, IAM UserGroup e S3 bucket para estudo.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      Tags:
        - Key: Name
          Value: EC2-Estudo

  MyIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: GrupoEstudo

  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: UsuarioEstudo
      Groups:
        - !Ref MyIAMGroup

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-estudo-1234567890

Outputs:
  EC2InstanceId:
    Description: ID da EC2 criada
    Value: !Ref EC2Instance

  IAMUserName:
    Description: Nome do usuário IAM
    Value: !Ref MyIAMUser

  IAMGroupName:
    Description: Nome do grupo IAM
    Value: !Ref MyIAMGroup

  S3BucketName:
    Description: Nome do bucket S3
    Value: !Ref MyS3Bucket
